### ISSUE TITLE
Could you provide other download links except dropbox?

### ISSUE THREAD

**Issue by ruhuasiyu** [ImCoolYeah105/Mechanization#1]
Hi, I'm a player from China. I'm very interested in your datapacks and I tried to download it. But thanks to the great firewall, most people in China can not visit dropbox. I also tried to download the files from the repo directly, but it seems that it's not complete (no tick.json)? So if it's convenient, could you provide maybe a zip in the repo? Thank you!

**Comment by Darkspyro911** [comment]
hi its two big of a file

On 5/13/18, ruhuasiyu <notifications@github.com> wrote:
> Hi, I'm a player from China. I'm very interested in your datapacks and I
> tried to download it. But thanks to the great firewall, most people in China
> can not visit dropbox. I also tried to download the files from the repo
> directly, but it seems that it's not complete (no tick.json)? So if it's
> convenient, could you provide maybe a zip in the repo? Thank you!
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ImCoolYeah105/Mechanization/issues/1


-- 
Marc-Andre Maurice
mauricemarcandre@gmail.com

**Comment by ImCoolYeah105** [comment]
The code on the repo was the latest full release. However, seeing as I doubt anyone cares about that (1.12 version), I've updated the code. However, you will still need the resourcepack, which can't be hosted in the code. What downloads sites will work for you? Easiest alternative would be google drive, but that might also be blocked.

**Comment by ruhuasiyu** [comment]
Maybe you can simply upload the resourcepack zip file to this repo? In fact, I can visit pmc, curseforge etc. 
Emm, forget it, I will borrow a vpn.

**Comment by Darkspyro911** [comment]
@ImCoolYeah105 infact you can with 1.13 just have it named
resources.zip than in the pack data file put 4 for the version
~Darkspyro911

On 5/14/18, ruhuasiyu <notifications@github.com> wrote:
> Maybe you can simply upload the resourcepack zip file to this repo? In fact,
> I can visit pmc, curseforge etc.
> Emm, forget it, I will borrow a vpn.
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/ImCoolYeah105/Mechanization/issues/1#issuecomment-389029940


-- 
Marc-Andre Maurice
mauricemarcandre@gmail.com

**Comment by ruhuasiyu** [comment]
@Darkspyro911 I think he knows that
