### ISSUE TITLE
Mechanical Manual is Gone

### ISSUE THREAD

**Issue by WanderingLynx** [ImCoolYeah105/Mechanization#10]
I watched Logdotzip's 2nd video about this datapack, and he showed  a mechanical manual with a crafting recipe. I tried it in-game, and it wasn't there. I also looked around in the files for crafting, and it isn't there either.

**Comment by ImCoolYeah105** [comment]
I tried to have an update with the manual before LDZ posted the video, but it's taking longer to implement than expected. I'll have it out sometime this weekend.

**Comment by WanderingLynx** [comment]
Ok, thanks! I'm looking forward to when that happens.  Also, is there a chance that like, in most mods, that the player starts the game with the manual?

**Comment by ImCoolYeah105** [comment]
It gives you the manual the first time you make the Machine Crafter (specifically as a reward for getting the advancement).

**Comment by WanderingLynx** [comment]
Thanks for clearing all this up. Makes a lot more sense now! 😄
