### ISSUE TITLE
Machines look very dark

### ISSUE THREAD

**Issue by MineCommanderCN** [ImCoolYeah105/Mechanization#102]
1. What datapack(s) do you have installed (including ones made by me- include version if possible).
Using datapacks Mechanization v2.3.0 and Datapack Utilities v2.2.0a.

2. Run /reload. Copy/paste or post a screenshot of what appears in chat (should say [Loaded <datapack> <version>]).
![image](https://user-images.githubusercontent.com/59791306/89484999-5ce77c80-d7d2-11ea-94b8-d0c71b02dfb8.png)

3. What environment are you running the datapack? (Vanilla single player, Vanilla multiplayer, Forge, fabric, spigot, bukkit, paper, optifine, realms, etc). Please specify exact Minecraft version as well.
Minecraft 1.16.1 with Fabric 0.8.0+build202.

4. What if happening vs. what you expect to happen?
![image](https://user-images.githubusercontent.com/59791306/89485522-8bb22280-d7d3-11ea-9ae9-d14413978ef9.png)
Rendered wrong machines in the picture, from left to right are Machine Crafting Table, Auto Jukebox, MSS Driver Bay and Grinder.
Many machines render unusual dark and it's hard to distinguish every single machine. It seems to happen only in 1.16 but not the 1.15, is this issue about the datapack or the game itself?

**Comment by ImCoolYeah105** [comment]
This is probably a 1.16 issue, however 1.16.2-prerelease 3 is supposed to fix this.
