### ISSUE TITLE
Manual deletes my worn armour and items from off hand

### ISSUE THREAD

**Issue by klay98** [ImCoolYeah105/Mechanization#103]
1. What datapack(s) do you have installed (including ones made by me- include version if possible).

[terracotta rotation wrench v1.1.0.zip](https://github.com/ImCoolYeah105/Mechanization/files/5047501/terracotta.rotation.wrench.v1.1.0.zip)
[track raw statistics v1.4.0.zip](https://github.com/ImCoolYeah105/Mechanization/files/5047502/track.raw.statistics.v1.4.0.zip)
[treasure gems v1.2.0.zip](https://github.com/ImCoolYeah105/Mechanization/files/5047503/treasure.gems.v1.2.0.zip)
[villager death messages v1.2.1.zip](https://github.com/ImCoolYeah105/Mechanization/files/5047504/villager.death.messages.v1.2.1.zip)
[villagerleashes.zip](https://github.com/ImCoolYeah105/Mechanization/files/5047505/villagerleashes.zip)
[wandering trades hermit edition v1.4.0.zip](https://github.com/ImCoolYeah105/Mechanization/files/5047506/wandering.trades.hermit.edition.v1.4.0.zip)
[wandering trades v1.4.0.zip](https://github.com/ImCoolYeah105/Mechanization/files/5047507/wandering.trades.v1.4.0.zip)
[armor statues v2.8.1.zip](https://github.com/ImCoolYeah105/Mechanization/files/5047508/armor.statues.v2.8.1.zip)
[Chunk-Loader-Datapack.zip](https://github.com/ImCoolYeah105/Mechanization/files/5047509/Chunk-Loader-Datapack.zip)
[classic fishing loot v1.1.0.zip](https://github.com/ImCoolYeah105/Mechanization/files/5047510/classic.fishing.loot.v1.1.0.zip)
[coordinates hud v1.2.0.zip](https://github.com/ImCoolYeah105/Mechanization/files/5047511/coordinates.hud.v1.2.0.zip)
[count mob deaths v1.1.0.zip](https://github.com/ImCoolYeah105/Mechanization/files/5047512/count.mob.deaths.v1.1.0.zip)
[custom nether portals v2.3.0.zip](https://github.com/ImCoolYeah105/Mechanization/files/5047513/custom.nether.portals.v2.3.0.zip)
[datapackutilities-v2-2-0a.zip](https://github.com/ImCoolYeah105/Mechanization/files/5047514/datapackutilities-v2-2-0a.zip)
[double shulker shells v1.3.0.zip](https://github.com/ImCoolYeah105/Mechanization/files/5047515/double.shulker.shells.v1.3.0.zip)
[dragon drops v1.3.0.zip](https://github.com/ImCoolYeah105/Mechanization/files/5047516/dragon.drops.v1.3.0.zip)
[durability ping v1.2.0.zip](https://github.com/ImCoolYeah105/Mechanization/files/5047517/durability.ping.v1.2.0.zip)
[gem villagers v4.3.1.zip](https://github.com/ImCoolYeah105/Mechanization/files/5047518/gem.villagers.v4.3.1.zip)
[graves v2.7.2.zip](https://github.com/ImCoolYeah105/Mechanization/files/5047519/graves.v2.7.2.zip)
[item averages v1.3.0.zip](https://github.com/ImCoolYeah105/Mechanization/files/5047520/item.averages.v1.3.0.zip)
[kill empty boats v1.1.0.zip](https://github.com/ImCoolYeah105/Mechanization/files/5047521/kill.empty.boats.v1.1.0.zip)
[krakenboss.zip](https://github.com/ImCoolYeah105/Mechanization/files/5047522/krakenboss.zip)
[Mechanization_v2.3.0.zip](https://github.com/ImCoolYeah105/Mechanization/files/5047523/Mechanization_v2.3.0.zip)
[multiplayer sleep v1.1.0.zip](https://github.com/ImCoolYeah105/Mechanization/files/5047524/multiplayer.sleep.v1.1.0.zip)
[nether portal coords v1.1.0.zip](https://github.com/ImCoolYeah105/Mechanization/files/5047525/nether.portal.coords.v1.1.0.zip)
[player head drops v1.1.0.zip](https://github.com/ImCoolYeah105/Mechanization/files/5047526/player.head.drops.v1.1.0.zip)
[redstone rotation wrench v1.1.0.zip](https://github.com/ImCoolYeah105/Mechanization/files/5047527/redstone.rotation.wrench.v1.1.0.zip)
[spawning spheres v1.1.0.zip](https://github.com/ImCoolYeah105/Mechanization/files/5047528/spawning.spheres.v1.1.0.zip)
[tag v2.1.0.zip](https://github.com/ImCoolYeah105/Mechanization/files/5047529/tag.v2.1.0.zip)

2. Run /reload. Copy/paste or post a screenshot of what appears in chat (should say [Loaded <datapack> <version>])

![2020-08-09_07 47 37](https://user-images.githubusercontent.com/69423412/89732451-a4f5e180-da14-11ea-98f1-bc53a5eb9a07.png)
.

3. What environment are you running the datapack? (Vanilla single player, Vanilla multiplayer, Forge, fabric, spigot, bukkit, paper, optifine, realms, etc). Please specify exact Minecraft version as well.

vanilla singleplayer with optifine

4. What if happening vs. what you expect to happen?

every time i hold the manual in my hand it deletes my worn armor including anything in my off hand
 simply placing the item in you hand and not interacting with it causes it to happen, this is especially problematic seeing as it spawns in your hand when you first load the datapack. 

i tried crafting my own manual to see if it still happens and it does.

**Comment by MineCommanderCN** [comment]
that's quite a LOT of datapacks...you may try to disable some one

**Comment by ImCoolYeah105** [comment]
It's a known issue, should have it fixed soon

**Comment by ImCoolYeah105** [comment]
Fixed in v2.3.0b
