### ISSUE TITLE
Help with nuclear reactors

### ISSUE THREAD

**Issue by Worlddominator05** [ImCoolYeah105/Mechanization#109]
I really want some help designing nuclear reactors, I understand the mechanics but mine keep blowing up. Can you or someone else make a tutorial on how to build reactors? I'm playing on realms with a friend and we would like to build a fission reactor.

**Comment by Worlddominator05** [comment]
How do I change the label it's not a bug

**Comment by ImCoolYeah105** [comment]
Typically the main misunderstanding is this here:

> If the reactor exceeds 2000 °C, then it will explode! To decrease the reaction rate, use a control rod. Keep in mind reaction rate is like acceleration- the temperature will not start decreasing until the reaction rate drops into the negatives, which can take some time after activating the control rod.

To rephrase, activating the control rod will slow the temperature increase, but will not immediately stop it. You have to activate the control rod early to stop the reactor from exploding.

Btw, I recommend joining the discord for generic datapack questions: https://discord.gg/6uJ4eJH
