### ISSUE TITLE
Zombies Follow Me When Holding Items From This Datapack

### ISSUE THREAD

**Issue by WanderingLynx** [ImCoolYeah105/Mechanization#11]
I was fooling around with features from this datapack, and I noticed that zombies, husks, and drowned  follow me when holding items from this datapack, regardless of my gamemode.

**Comment by ImCoolYeah105** [comment]
Mechanization uses villager based right click detection, so when you hold something in front of you there is an actually an invisible villager floating in front of your face. There is very little I can do about this.
