### ISSUE TITLE
Tinker Table Duplication

### ISSUE THREAD

**Issue by D-Crusader** [ImCoolYeah105/Mechanization#110]
1. What datapack(s) do you have installed (including ones made by me- include version if possible).

Datapack utitlities v2.2.1
Mechanization v2.3.2

2. Run /reload. Copy/paste or post a screenshot of what appears in chat (should say [Loaded <datapack> <version>]).

3. What environment are you running the datapack? (Vanilla single player, Vanilla multiplayer, Forge, fabric, spigot, bukkit, paper, optifine, realms, etc). Please specify exact Minecraft version as well.

1.16.2 vanilla single player

4. What if happening vs. what you expect to happen?

Should a player place any item in the 'blank' area of the table while there is a tinkerable item...it gives you multiple of the placed item instead of the same amount....i believe this isn't intentional

**Comment by ImCoolYeah105** [comment]
Yeah, that's definitely not good...

**Comment by ImCoolYeah105** [comment]
Fixed in v2.3.2a
