### ISSUE TITLE
Which folder should I move MechConfig_vx.x.x.zip to?

### ISSUE THREAD

**Issue by Frank-fjh** [ImCoolYeah105/Mechanization#111]
Which folder should I move MechConfig_vx.x.x.zip to?
I had moving DatapackUtilities_v2.2.1d.zip and Mechanization_v2.3.2.zip to the folder datapacks and the game have show the: Loaded Mechanization v2.3.2
But I can't find any blocks ! Although I can find and dig the special ore, they still can't be use.

**Comment by ImCoolYeah105** [comment]
MechConfig is optional. Only use it if you want to change the default values.

It is impossible to add blocks/items to the creative inventory, use `/function give:mech_all` instead. Also, you will have to break and replace existing furnaces to smelt ores.
