### ISSUE TITLE
Decompressor Disappeared when using the wrench

### ISSUE THREAD

**Issue by Pokemon5252525252** [ImCoolYeah105/Mechanization#112]
Installed Datapacks: 'Mechanization' and 'Datapack Utils'

When using the /reload command shows
[Loaded Datapack Utils v2.1.4]
[Loaded Mechanization v2.2.2]

Using a 1.15.2 vanilla Minecraft server for this datapack

I expect for the Decompressor to drop when I. use the wrench

**Comment by ImCoolYeah105** [comment]
Fixed in v2.3.2a
