### ISSUE TITLE
Alloy furnace creates wrong output

### ISSUE THREAD

**Issue by Akax1337** [ImCoolYeah105/Mechanization#115]
1. What datapack(s) do you have installed (including ones made by me- include version if possible). I only have Mechanization and the utils one,(2.3.2 an 2.2.1d)

2. Run /reload. Copy/paste or post a screenshot of what appears in chat (should say [Loaded <datapack> <version>]).
![imagen](https://user-images.githubusercontent.com/77030077/103710658-dec41780-4fb5-11eb-90f6-c96217446117.png)
ignore the login part, that's a plugin i have

3. What environment are you running the datapack? (Vanilla single player, Vanilla multiplayer, Forge, fabric, spigot, bukkit, paper, optifine, realms, etc). Please specify exact Minecraft version as well.
I have Minecraft Multiplayer 1.16.3 with Paper release 253(latest for 1.16.3).

4. What if happening vs. what you expect to happen?
I created Conductive Ingot and then queued items through a hopper to create a Crystal Composite. What i expected was that the Alloy furnace would not start until i took the conductive Ingots. What happened is that the Alloy furnace created 1 Conductive Ingot by using the ingredients to make 1 Crystal Composite.

**Comment by ImCoolYeah105** [comment]
Fixed in v2.3.2a
