### ISSUE TITLE
Can't enter the nether or the end

### ISSUE THREAD

**Issue by That1Game** [ImCoolYeah105/Mechanization#116]
this world is a singleplayer world and when entering a nether portal/fully activated end portal nothing happens

![image](https://user-images.githubusercontent.com/79281748/108413334-e6075380-71f8-11eb-9e07-ed4e0cd28e67.png)

![image](https://user-images.githubusercontent.com/79281748/108413681-4bf3db00-71f9-11eb-95f7-3c12b181ad97.png)

**Comment by ImCoolYeah105** [comment]
Mech does not use "experimental settings" (custom world generation), and as far as I know cannot cause this to happen. It is likely something else.

In the future please fill out the bug template form.
