### ISSUE TITLE
Ores don't generate

### ISSUE THREAD

**Issue by LeonidMem** [ImCoolYeah105/Mechanization#117]
1. Here's the list:

- More Totems
- Illager Fortresses
- Wild Worlds
- BAC Advancements
- ItemFrameColor
- Mechanization 2.3.2
- DatapackUtilities 2.2.1

2. ![image](https://user-images.githubusercontent.com/61764553/116733941-3293ba00-aa06-11eb-9529-17f005cad1e4.png)

3. Vanilla singleplayer, 1.16.5

4. So, I don't have any new ores in the caves and I don't know why. Maybe it was because when I created the world I've forgotten to install DatapackUtilities, but after 5 minutes I've installed it. And I don't have any new ores in new chunks too. What do I suppose to do?

**Comment by ImCoolYeah105** [comment]
Wild Worlds uses chunk scanning and is therefor incompatible with DU/Mech (really weird that it's uses experimental settings and chunk scanning at the same time).

Willian Wythers' Overhauled Overworld is a good reworked-overworld world gen pack that is known to be compatible with Mech: https://www.planetminecraft.com/data-pack/william-wythers-overhauled-overworld/
