### ISSUE TITLE
I have a problem...

### ISSUE THREAD

**Issue by GamesMaster2** [ImCoolYeah105/Mechanization#13]
The recipe that Logdotzip used to make the manual does not work for me!
https://youtu.be/OCp-US8P13U?t=2m12s

EDIT:Just saw the post you made about the manual!

**Comment by ImCoolYeah105** [comment]
I tried to have an update with the manual before LDZ posted the video, but it's taking longer to implement than expected. I'll have it out sometime this weekend.
