### ISSUE TITLE
all my items and blocks except ores do not have right textures...

### ISSUE THREAD

**Issue by kosplay45** [ImCoolYeah105/Mechanization#17]
i got a furnace gen. and a teir one battery but when i put my world on 1.13 (pre 3) all the textures were gone!

i treid downloading the resources and the datapack again but it still does not work!

**Comment by ImCoolYeah105** [comment]
Pre 3 broke resourcepacks. Not much I can do about this. For now I would recommend using Pre 2, or wait for Pre 4 to see if it gets fixed.
