### ISSUE TITLE
Use translate instead plain string in display name?

### ISSUE THREAD

**Issue by ruhuasiyu** [ImCoolYeah105/Mechanization#19]
Could you replace the string in display name to translate json? Something like item.mechanization.battery?
So that the people using other languages can easily make the translated text in resources?

**Comment by Darkspyro911** [comment]
i don't think how that works Minecraft does not use Google™ translate
if it does all other language will not be said right since Google™
Translate does word by word

On 7/7/18, ruhuasiyu <notifications@github.com> wrote:
> Could you replace the string in display name to translate json? Something
> like item.mechanization.battery?
> So that the people using other languages can easily make the translated text
> in resources?
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ImCoolYeah105/Mechanization/issues/19


-- 
Marc-Andre Maurice
mauricemarcandre@gmail.com

**Comment by ImCoolYeah105** [comment]
Yes, that's on my todo list. Not sure exactly when though.

**Comment by ruhuasiyu** [comment]
Great

**Comment by ImCoolYeah105** [comment]
The latest update changes everything to use translate names.
