### ISSUE TITLE
Energy Relays Cannot Supply Power to Quantum Storage Units

### ISSUE THREAD

**Issue by ImCoolYeah105** [ImCoolYeah105/Mechanization#2]
When in export mode, energy relays push power outside of the Quantum Network's update loop, which destroys the power.

**Comment by Darkspyro911** [comment]
true also in inport mode it takes power from the ter 1 to 3 battery
and puts in the quantum battery, is this intention?

On 5/28/18, ImCoolYeah105 <notifications@github.com> wrote:
> When in export mode, energy relays push power outside of the Quantum
> Network's update loop, which destroys the power.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ImCoolYeah105/Mechanization/issues/2


-- 
Marc-Andre Maurice
mauricemarcandre@gmail.com

**Comment by ImCoolYeah105** [comment]
Fixed in 2.1 Prerelease 2
