### ISSUE TITLE
Not installing correctly? How to verify?

### ISSUE THREAD

**Issue by tmajibon** [ImCoolYeah105/Mechanization#20]
I've been trying to install this, but I can't seem to get it working right.

Resource pack installed, data pack installed (wouldn't register at all until I unzipped it).

I can get the loading message, and the related tags are available from the debug (F3) view.

I've tried opening up creative mode and the only item I can find is the machine crafting table, but it seems to just spawn as a damaged anvil and function as such (though the displayed name is correct).

The advancements seem to appear correctly as well.

I've tried digging for an extended period around layer 30, and while I've seen many many vanilla ores I haven't been able to find any of the copper or tin ores that are supposed to appear.

This is with 2.0.2c from curseforge, though the resource pack is just 2.0.2b (curseforge doesn't list a c option there)

Any ideas? And is there a way to shortcut spawning the machines with creative/cheats to verify?

**Comment by ImCoolYeah105** [comment]
Adding custom items to the creative menu is not a possible using datapacks. You can give yourself all the items using the command /function give:mech_all

You can verify custom ores are generating by going into spectator mode. You'll be able to see them through the ground. If they are not generating, let me know and I'll look into it (changes in minecraft sometimes break these things).

**Comment by Darkspyro911** [comment]
Did you put it in the datapack folder?


Sent from Mail for Windows 10

From: Chris Martin
Sent: July 19, 2018 4:57 PM
To: ImCoolYeah105/Mechanization
Cc: Subscribed
Subject: [ImCoolYeah105/Mechanization] Not installing correctly? How toverify? (#20)

I've been trying to install this, but I can't seem to get it working right.
Resource pack installed, data pack installed (wouldn't register at all until I unzipped it).
I can get the loading message, and the related tags are available from the debug (F3) view.
I've tried opening up creative mode and the only item I can find is the machine crafting table, but it seems to just spawn as a damaged anvil and function as such (though the displayed name is correct).
The advancements seem to appear correctly as well.
I've tried digging for an extended period around layer 30, and while I've seen many many vanilla ores I haven't been able to find any of the copper or tin ores that are supposed to appear.
This is with 2.0.2c from curseforge, though the resource pack is just 2.0.2b (curseforge doesn't list a c option there)
Any ideas? And is there a way to shortcut spawning the machines with creative/cheats to verify?

**Comment by tmajibon** [comment]
The function seems to spawn everything just fine.

Didn't realized spectator mode worked like no-clip. Didn't see any new ores from spectator mode, even flew some distance to verify.

**Comment by ImCoolYeah105** [comment]
I was able to fix the issue with ore gen and uploaded a new version (2.0.2d). Note that this will only apply in new chunks.

**Comment by Darkspyro911** [comment]
do /debug start wait a few minutes than do /debug stop and send the
debug profile

On 7/19/18, ImCoolYeah105 <notifications@github.com> wrote:
> Closed #20.
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/ImCoolYeah105/Mechanization/issues/20#event-1743755600


-- 
Marc-Andre Maurice
mauricemarcandre@gmail.com

**Comment by tmajibon** [comment]
It seems to at least partially fixed it... when I generated a new world and loaded the datapack it clearly spawned the ores, but only around the spawn area... I didn't count exactly how far, but probably only a few chunks out it stops generating ores.

I attached a picture at the edge of it showing it from one of the corners in spectator mode.

This is a new map, freshly loaded. (Created world, exited, loaded datapack, reloaded world).

As a note, I also tried wiping the chunks and forcing it to reload, and it did the same thing.

![capture](https://user-images.githubusercontent.com/5880760/42980895-fca34b96-8b9e-11e8-8a14-da6bd46d081b.PNG)

**Comment by tmajibon** [comment]
Oh, and thanks for the quick turn around! You rock!

**Comment by ImCoolYeah105** [comment]
The ore generator doesn't fill in the chunks as they generate, but instead a 5x5 area around the player as you move around. Currently there is no way to plug directly into the chunk generator, so other methods have to be used. It also doesn't generate ores while in spectator mode (lag prevention measure since spectators can fly very fast), but moving around in creative will cause ores to generate in.

**Comment by tmajibon** [comment]
That's smooth! Thanks!

**Comment by Darkspyro911** [comment]
and it only gens in the loaded chunks if you teleport

On 7/19/18, Chris Martin <notifications@github.com> wrote:
> That's smooth! Thanks!
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/ImCoolYeah105/Mechanization/issues/20#issuecomment-406477656


-- 
Marc-Andre Maurice
mauricemarcandre@gmail.com
