### ISSUE TITLE
1.13?

### ISSUE THREAD

**Issue by GamesMaster2** [ImCoolYeah105/Mechanization#22]
It does not really work in 1.13 so when will that release?

**Comment by ImCoolYeah105** [comment]
The latest version (2.0.2d) is built for 1.13 and in fact only works for that version. If you are having problems getting it to work, double check you have installed in correctly (if it helps, there are video tutorials on the wiki under Installation Instructions).

**Comment by GamesMaster2** [comment]
My Mechanization resource pack does not work correctly

**Comment by Darkspyro911** [comment]
did you redownload the resource pack after 7/18/2018? because the
resource pack was updated on that date

On 7/22/18, GamesMaster2 <notifications@github.com> wrote:
> My Mechanization resource pack does not work correctly
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ImCoolYeah105/Mechanization/issues/22#issuecomment-406845363


-- 
Marc-Andre Maurice
mauricemarcandre@gmail.com
