### ISSUE TITLE
Wiki clarity

### ISSUE THREAD

**Issue by tmajibon** [ImCoolYeah105/Mechanization#23]
I've been having a little bit of trouble trying to follow the instructions/guides because the pictures of recipes are not completely clear about what items are what?

For instance I can't figure out what the item is in the corners of the Furnace Generator recipe on the Energy Generators page.

My suggestion is to accompany each recipe with a text "ingredients" list.

**Comment by ImCoolYeah105** [comment]
Added an ingredients tagline to most recipe on the wiki.
