### ISSUE TITLE
Ore Density/Veins

### ISSUE THREAD

**Issue by tmajibon** [ImCoolYeah105/Mechanization#24]
I'm aware that this is definitely easier said than done, but I figured I'd make an issue for it for discussion as well as for others who may have less awareness of the challenge to be able to see the response.

My biggest complaint so far about this "mod" is that the ores all generate in single blocks, unlike vanilla ores which generate in veins.

The problem of this is that it dramatically increases the difficulty of finding the ores (requiring thorough mining strategies), and it also dramatically reduces the output.

In the time that I gathered over 100 iron, I just finally managed to get 4 tin.

As I'm aware that you're not able to hook into the ore generation routines at this time, the thoughts are:

* Would it be possible to generate the ores as larger structures?
* As a stop-gap, perhaps allow the ores to be more efficient and generate multiple bars when smelted?

**Comment by ImCoolYeah105** [comment]
The problem is that I have to balance the number of ores in the ground with performance. While player heads are easier on the fps than other methods of custom blocks, having hundreds of them underground adds ups. There are a few solutions I've thought of, but all them make compromises in one way or another.
You can use the Grinder to get more out of your ores of course, but it'll take a bit or resources to get there.

**Comment by tmajibon** [comment]
I figured there were various problems like that, the big problem is that even the grinder feels lacking due the fact that I just went through about 2 iron picks (one is halfway down, but it's also unbreaking 1) to find 1 tin (23 iron though).

At this point the ore is the big stop gap burning me out... I'm wondering if it might be better to rig a system using vanilla ores instead? Maybe drop the cost of the alloy furnace and have recipes to generate the base ores or equivalent ores?

Regardless, your method of inserting ores is genius, I just wish it worked out better for gameplay :'-(

**Comment by tmajibon** [comment]
Just for reference: at this point I'd consider it a good deal even if it cost me 10 iron to make 1 tin/copper

**Comment by ImCoolYeah105** [comment]
During my play through, I found I was able to get enough ore to start with by splunking. Strip mining was very inefficient and netted fairly little. The grinder effectively halves the cost of machines, and once you have it the quarry isn't too hard to get which can really speed up finding ores.

Might go through and take another look at it. Maybe there is some method I can come up with to help get more ores without just physically generating more.

**Comment by tmajibon** [comment]
I'll take a stab at more spelunking and let you know how that works out.

**Comment by tmajibon** [comment]
Spelunking definitely got me more faster, it's not my preferred way to mine but it looks like it's by far the way to go for this generation.

Now I'm just stuck with trying to figure out what's in the corners of the furnace recipe... (see my other issue)

**Comment by ImCoolYeah105** [comment]
v2.0.4 released which reworks ore generation.
