### ISSUE TITLE
Ore Duplication in the Machine Crafting Table

### ISSUE THREAD

**Issue by Versimno** [ImCoolYeah105/Mechanization#25]
Putting the ore in the top left and putting the flint and steel next to it, the flint and steel is consumed and the ore stays, therefore allowing you to have infinite of any ore at the cost of flint and steels.

I'm using the latest version, 2.0.3c on MC 1.13

**Comment by Versimno** [comment]
![tin dupe](https://user-images.githubusercontent.com/39289537/43176034-a3066180-8f87-11e8-9b11-ac26f3c15fca.gif)

**Comment by ImCoolYeah105** [comment]
Fixed in 2.0.3d
