### ISSUE TITLE
manifest Missing

### ISSUE THREAD

**Issue by RiowHatake** [ImCoolYeah105/Mechanization#26]
My game the pack is not working that i am missing the manifest in mechresources i not sure how to fix this

**Comment by Darkspyro911** [comment]
revert to a older one which before beta works than rework off of that

On 7/29/18, RiowHatake <notifications@github.com> wrote:
> My game the pack is not working that i am missing the manifest in
> mechresources i not sure how to fix this
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ImCoolYeah105/Mechanization/issues/26


-- 
Marc-Andre Maurice
mauricemarcandre@gmail.com

**Comment by ImCoolYeah105** [comment]
Manifest? Are you try to install this like a mod? Datapacks are installed differently, here's the installation instructions: https://github.com/ImCoolYeah105/Mechanization/wiki/Installion

**Comment by RiowHatake** [comment]
I have tried this I don't this instructs works for windows 10 edition.

**Comment by ImCoolYeah105** [comment]
Oh, datapacks are Java edition exclusive. Bedrock does not support features required to make them.

**Comment by Darkspyro911** [comment]
in bedrock it called addons but imcoolyeah105 will have to rewrite the
whole pack since commands are different in bedrock

On 8/2/18, ImCoolYeah105 <notifications@github.com> wrote:
> Oh, datapacks are Java edition exclusive. Bedrock edition does not support
> features required to make them.
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/ImCoolYeah105/Mechanization/issues/26#issuecomment-409972115


-- 
Marc-Andre Maurice
mauricemarcandre@gmail.com
