### ISSUE TITLE
[suggestion] in book recipes 

### ISSUE THREAD

**Issue by SDUBZ** [ImCoolYeah105/Mechanization#28]
Just wondering if you could add the item name in the book recipes of items because from eye sight especially those that maybe color blind could see what items are used in recipes, there was many times i had to myself cheat in items after grinding away for ages and find out i had the wrong block

**Comment by Darkspyro911** [comment]
Oh that book is off  from the wiki so both the book and wiki will need
updating so that could take awhile.

**Comment by ImCoolYeah105** [comment]
The in-game book is a tad crammed as it is, but I've had numerous requests for this, so I'll at least add it to the wiki (eventually...)

**Comment by SDUBZ** [comment]
okay thank you

**Comment by ImCoolYeah105** [comment]
Added ingredients tagline to most recipe on the wiki. Doing a minor manual rework, I'll see about making recipe more clear.
