### ISSUE TITLE
Please Fix ASAP I really enjoy the datapack

### ISSUE THREAD

**Issue by BrendonGomez** [ImCoolYeah105/Mechanization#3]
The problem is that the tin ore copper ore etc will crash your game upon spawning in if its in a ocean im playing on a survival island so theres more water then land this also happened on regular worlds aswell if your in the ocean long enough. Here's my crash log and yes ive tried removing my other datapack that has to do with submarines to see if it was the problem which it wasn't and I also removed the texture pack either way it still crashes. So I decided to use only your data pack and then see if it crashes and it does and when I remove your data pack it no longer crashes
[crash-2018-06-02_16.30.00-client.txt](https://github.com/ImCoolYeah105/Mechanization/files/2065509/crash-2018-06-02_16.30.00-client.txt)

I'm sure I can fix by not allowing the heads to spawn in water or by changing it to a different block if Mojang would have make it where renamed items don't default back to their normal names when you break them. Even though I may be able to fix this I figured I should inform you so that you can have it fixed for others when they download your incredible datapack

**Comment by ImCoolYeah105** [comment]
I was able to replicate the crash, but I'm uncertain as to the specific cause so it warrants further investigation. It appears to be a bug with Minecraft itself, so once I have sufficient information I'll open a mojang bug report.

**Comment by Darkspyro911** [comment]
ok the bot might say it allredy there since i was the first to make it
~Darkspyro911

On 6/2/18, ImCoolYeah105 <notifications@github.com> wrote:
> I was able to replicate the crash, but I'm uncertain as to the specific
> cause so it warrants further investigation. It appears to be a bug with
> Minecraft itself, so once I have sufficient information I'll open a mojang
> bug report.
>
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ImCoolYeah105/Mechanization/issues/3#issuecomment-394130383


-- 
Marc-Andre Maurice
mauricemarcandre@gmail.com

**Comment by BrendonGomez** [comment]
I'm not certain but I believe it has to do with the ores trying to be loaded into water because if I'm on land nothing happens. If its possible try adding a line of code to prevent your ores from being spawned in water and if that works let me know. If not I really appreciate your time that you've put into developing. One last thing in the future can you make the titanium armor have a texture instead of using the diamond armor texture. Thanks for your support.

**Comment by BrendonGomez** [comment]
I'm really sorry about this but the 1.13 pre release snapshot has been released and I tried playing your datapack on it and it still crashes when I go in the ocean the reason I wanted to let you know is because its a 1.13 pre release snapshot so I was wondering if you can submit a bug to Mojang about what's happening before the next release because I belive the next release is going to be the official 1.13 update

**Comment by ImCoolYeah105** [comment]
I've made some changes to the world gen that should make this crash far less common. I was unable to make the crash occur post-changes, though I imagine it is still possible (just very rare). A patch will be released shortly.
