### ISSUE TITLE
[Question] Plants and Food?

### ISSUE THREAD

**Issue by Burgersim** [ImCoolYeah105/Mechanization#32]
I used your data pack and I am really impressed what seems to be possible without mods, in the new Minecraft 1.13, so I wanted to ask, if you think it would be possible to add other foods, seeds and plants to farm and eat, that e.g. grow custom player heads as items, with food values? Would that be possible through the use of a datapack?

Also, is there an in game book for the recipes of your data pack?

Thanks in advance, and greetings

**Comment by ruhuasiyu** [comment]
For food, if you don't need to change the texture, e.g eating a rabbit stew with a special tag gives you the effect of saturation. Or modify the carrot on a stick texture, to realise eat food via a single right click, but it can be stacked.

For the seeds, if the items are still wheat seeds or something else, with special tags, you can define the event after right click it on a farmland, then use modified textures in the armor stand. But if you want to customize the texture, it can not be stacked and I think only carrot on a stick is easy to realize the right click event.

Beacause you cannot put an image on a book (maybe possible via modifying the font), you can only see texts on a book. My way is creating a special machine to show the recipes, use Q or Shift click to realize some functions like NEI/JEI.

Beside, I am not the author, I am another vanilla modder ;)

**Comment by Burgersim** [comment]
Ah ok, I thought maybe someting like melons and pumpkins would be possible, but growing custom player heads, that look like, tomatoes or other stuff for example, but maybe, I'm being a bit too naive ^^* just saw thhat the treasure gems were able to be stacked, and they were custom player heads, so I thought maybe, that'd be possible too for stuff like food

**Comment by ImCoolYeah105** [comment]
There is an in-game "book" called the Mechanical Manual (it's basically just an item textured to look like a book and remodeled to fill your whole screen). You should get it the first time you create a Machine Crafting Table, but if not you can craft with with a book surrounded by 4 redstone (in the Machine Table).

The next major update to Mechanization will be the Genetics update, which will add new crops, animals, foods, and ways to manipulate their genetics to create custom plants. I'll be a few months before this update is ready for release though.

**Comment by Burgersim** [comment]
Wow, that does sound really awesome tbh, like exactly what I would love on my Server, but I always wondered if that'd be possible wihout mods, I always wanted more crops, more machines, eventually magic (wizardry datapack looks really nce in that regard), and maybe extra decoration, it'd be awesome if you could make recipes for custom mob heads with the recipe system in 1.13... but I guess that's not possible...
