### ISSUE TITLE
Manual is on spigot 1.13 server broken in mechanization version 2.0.4b

### ISSUE THREAD

**Issue by OmegaRogue** [ImCoolYeah105/Mechanization#35]
the manual wont open

**Comment by simon511000** [comment]
+1

**Comment by ImCoolYeah105** [comment]
Spigot blocks feature that are currently used to make the manual function, and so far they have denied fixing it. A small rework of the manual is being done that should make it compatible.

**Comment by OmegaRogue** [comment]
also there is no function for the recipe for the quarry

**Comment by ImCoolYeah105** [comment]
Fixed in 2.0.5
