### ISSUE TITLE
Quarry recipe

### ISSUE THREAD

**Issue by OmegaRogue** [ImCoolYeah105/Mechanization#38]
there is no function for the recipe for the quarry

**Comment by ImCoolYeah105** [comment]
What do you mean "There is no function." Is the recipe not working? If you were looking at the source code and saw there was no function for it, that's because only certain types of recipes get their own functions.

**Comment by OmegaRogue** [comment]
The recipe doesnt work

**Comment by OmegaRogue** [comment]
It wont craft it

**Comment by ImCoolYeah105** [comment]
Fixed in 2.0.5
