### ISSUE TITLE
im doomed

### ISSUE THREAD

**Issue by kosplay45** [ImCoolYeah105/Mechanization#39]
i got some tin on 1.13.1 MC version, i put it in the workbench, but no tin ingots. this is horrible because i need tin to make the frame... pleese help

**Comment by ImCoolYeah105** [comment]
You have to combine the ore with a flint & steel in the Machine Crafting Table.
If this in fact what you're doing and it's not working, respond with your Mechanization version and the game log and I'll reopen the issue.
