### ISSUE TITLE
Nice datapack but...

### ISSUE THREAD

**Issue by GamesMaster2** [ImCoolYeah105/Mechanization#4]
It would be really nice if you could try to add a crafting manual inside the datapack, it would just make it more convenient!

**Comment by Darkspyro911** [comment]
i agree i hope ImCoolYeah105 agrees ~ Darkspyro911

On 6/3/18, GamesMaster2 <notifications@github.com> wrote:
> It would be really nice if you could try to add a crafting manual inside the
> datapack, it would just make it more convenient!
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ImCoolYeah105/Mechanization/issues/4


-- 
Marc-Andre Maurice
mauricemarcandre@gmail.com

**Comment by ImCoolYeah105** [comment]
I'm looking into ways of doing this- I have a few ideas but nothing concrete. It's surprisingly hard to display custom recipes in-game. If you have any ideas, let me know.

**Comment by Darkspyro911** [comment]
not in game just put the picter in a folder with the download

Sent from Mail for Windows 10

**Comment by BrendonGomez** [comment]
Plugins like essentials have commands to see how to craft items and all it does it pull up a crafting table gui with the items in it. I believe essentials is open source I may be wrong but maybe you can get a good understanding of how its done and see if you can implement it into the data pack. I'm aware that the datapack is coded differently then plugins are.


Sidenote* How so you get plutonium is it even implamented

**Comment by Darkspyro911** [comment]
plutonium is created by useing a empty fuel cell in the centrifuge

On 6/5/18, BrendonGomez <notifications@github.com> wrote:
> Plugins like essentials have commands to see how to craft items and all it
> does it pull up a crafting table gui with the items in it. I believe
> essentials is open source I may be wrong but maybe you can get a good
> understanding of how its done and see if you can implement it into the data
> pack. I'm aware that the datapack is coded differently then plugins are.
>
>
> Sidenote* How so you get plutonium is it even implamented
>
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/ImCoolYeah105/Mechanization/issues/4#issuecomment-394618136


-- 
Marc-Andre Maurice
mauricemarcandre@gmail.com

**Comment by BrendonGomez** [comment]
You Should Create a machine/tool called a sieve it where you can mesh things and get different things from meshing them like meshing gravel could give u flint bones iron cooper anything u want really

**Comment by Darkspyro911** [comment]
join the discord and suggest that with the Mechanization Development community

On 6/11/18, BrendonGomez <notifications@github.com> wrote:
> You Should Create a machine/tool called a sieve it where you can mesh things
> and get different things from meshing them like meshing gravel could give u
> flint bones iron cooper anything u want really
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/ImCoolYeah105/Mechanization/issues/4#issuecomment-396130322


-- 
Marc-Andre Maurice
mauricemarcandre@gmail.com

**Comment by ImCoolYeah105** [comment]
I've released beta version 2.0.2.r3, which includes the new Mechanical Manual. Still not 100% implemented, but I wanted it to be available.

**Comment by ImCoolYeah105** [comment]
Yes, there were no back-end changes in 1.13-pre2. However, if something doesn't work as expected, please report.
