### ISSUE TITLE
Targetting(?) issue after using manual

### ISSUE THREAD

**Issue by jonqrandom** [ImCoolYeah105/Mechanization#40]
i scroll-wheeled away from the manual, and since then i've had to try multiple angles to open inventories; i pretty much have to do a little dance before right-clicking blocks with inventories actually registers and opens them. 
i've noticed the block-selection highlight doesn't show up until i can open them either, so i'm guessing maybe the guide prevents accidental right-clicks while it's equipped, and that function just didn't stop?

i tried taking the manual out of my inventory, i tried restarting, i tried using the manual and then selecting another hotbar slot with number keys, i tried closing the manual by dropping it - none of those helped.

additionally, when using the manual after this issue developed, i had to left-click multiple times to get it to turn one page (right-click worked fine though). it wasn't doing that the first time i read it.

UPDATE:
Eclipsion13 in the discord explained that the manual summons a villager for right-click detection, so i tried `/kill @e[type=minecraft:villager]`, which fixed the issue. i haven't seen a village yet, so i don't know if the 22 entities killed were real villagers or related to the issue.

**Comment by ImCoolYeah105** [comment]
Sounds like an issue with Datapack Utils. I’ve had problems in the past with it leaving villagers behind. Has this issue happened again, or was it one-time?

**Comment by jonqrandom** [comment]
it's happening fairly often, and i think (i've just been playing and occasionally /killing villagers) that pretty much all of the tools and placeables are triggering it.

**Comment by ImCoolYeah105** [comment]
Updated to DU 1.4.1. Theoretically should fix this issue.
