### ISSUE TITLE
Can't craft machine barrel and magazine

### ISSUE THREAD

**Issue by BTVoidX** [ImCoolYeah105/Mechanization#43]
![04-10-2018 173715](https://user-images.githubusercontent.com/37330718/46477651-29b1bc00-c7fc-11e8-8100-6d851eb318ea.png)
![04-10-2018 170831](https://user-images.githubusercontent.com/37330718/46476145-7dbaa180-c7f8-11e8-9c9d-1a512ff990fc.png)
(Tried with gold ingots and conductive ingots)

![04-10-2018 171607](https://user-images.githubusercontent.com/37330718/46476434-37197700-c7f9-11e8-8a4c-bef71b977f11.png)

**Comment by ImCoolYeah105** [comment]
The recipes use crystal composite (which is not super obvious from the book, I'm working on that).

**Comment by Darkspyro911** [comment]
it is it a  different clour and it enen says unless you are colored blind

On 10/4/18, ImCoolYeah105 <notifications@github.com> wrote:
> Closed #43.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ImCoolYeah105/Mechanization/issues/43#event-1884687124


-- 
Marc-Andre Maurice
mauricemarcandre@gmail.com

**Comment by Darkspyro911** [comment]
wrong ingunts on top an buttom

On 10/4/18, BTVoidX <notifications@github.com> wrote:
> ![04-10-2018
> 170229](https://user-images.githubusercontent.com/37330718/46476138-7abfb100-c7f8-11e8-89e5-16c87769cd71.png)
>
> ![04-10-2018
> 170831](https://user-images.githubusercontent.com/37330718/46476145-7dbaa180-c7f8-11e8-9c9d-1a512ff990fc.png)
>
>
>
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ImCoolYeah105/Mechanization/issues/43


-- 
Marc-Andre Maurice
mauricemarcandre@gmail.com
