### ISSUE TITLE
Tin destroyed when mining

### ISSUE THREAD

**Issue by HotPocky** [ImCoolYeah105/Mechanization#50]
While I was mining (specifically for tin), it dropped two half-slabs (placeholders, probably), they went into my hotbar and then disappeared from my inventory. It didn't do this yesterday and the only difference is I'm wearing armour and using a diamond pickaxe instead of an iron one.

**Comment by curtoman14** [comment]
I'm having the same issue. Maybe 1 in 10 of the new oars I mine actually go into my inventory. They turn into half slabs and disappear It doesn't matter what pickaxe I use or if I'm wearing armor.

**Comment by ewalk40** [comment]
I am also still having this issue, hopefully the update will be released soon, kinda breaks it for me

**Comment by ImCoolYeah105** [comment]
Should be fixed in 2.1 Prerelease 2
