### ISSUE TITLE
How will this data pack change now that the new 1.14 snapshots came out? (Question)

### ISSUE THREAD

**Issue by Mario3264** [ImCoolYeah105/Mechanization#51]
Just a question of what might happen, not forcing you to make it a little better using 1.14's technical stuff like the CustomModelData tag.

**Comment by ImCoolYeah105** [comment]
I will definitely be upgrading to the new 1.14 features- CustomModelData opens up a lot of possibilities, and the new data copy even more. Existing machines and things probably won't change too much, apart from optimizations made possible by new features.

I won't be upgrading to 1.14 right away. I'm going to wait for the snapshots to stabilize a bit. I expect the '1.14' update to come out around the same time as 1.14 itself.

**Comment by Darkspyro911** [comment]
there is one promble /data modify now requires a block with that data in it

On 10/28/18, ImCoolYeah105 <notifications@github.com> wrote:
> Closed #51.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ImCoolYeah105/Mechanization/issues/51#event-1930753996


-- 
Marc-Andre Maurice
mauricemarcandre@gmail.com
