### ISSUE TITLE
Add Fish to Bio Gen

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [ImCoolYeah105/Mechanization#55]
Hi, here is a little list of features request:

bio generator: since the auto-fisher produce an insane amount of fish could you add it to the bio generator, even 1kw would be good, because for example I'm voiding all the fish since it's completely useless(i filter those and push into lava);

enchant2experience: a machine similar to the disenchanter but that it can convert useless books(fire prot, blast prot, bane of ant, etc) into bottles of experience, it doesn't need to be the precise exp cost, half or even 1 bottle would be good enough, or add enchanted books to the ender generator so those books can be usefull for something;

thank you for your time.

**Comment by ImCoolYeah105** [comment]
1. This sounds pretty good. Overall I think the bio gen needs a buff, so that would help.

2. This sounds a bit overpowered. Combining the auto fisher, disenchanter, and XP tank already makes enchanting really easy. Maybe I can come up with a  good use for them though.

**Comment by ImCoolYeah105** [comment]
The grindstone in that latest snapshots allows for turning enchanted items (including books) into XP, so I'm going to close that part of the suggestion.

**Comment by ImCoolYeah105** [comment]
Fixed in 2.1 Prerelease 2
