### ISSUE TITLE
Phantom teleporters

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [ImCoolYeah105/Mechanization#57]
Hi,

I moved one of my teleporter to a new location but it inconsistently teleport me to the old location, what should I do?

**Comment by ImCoolYeah105** [comment]
Well, you can remove all teleporter markers with this command: `/kill @e[type=area_effect_cloud,tag=mech_tele]` (this won't remove the teleporter itself). However, this will require you to replace all existing teleporters.

I don't know exactly what is causing this issue, but I'm looking into it.

**Comment by ImCoolYeah105** [comment]
Fixed in 2.1 Prerelease 2
