### ISSUE TITLE
Suggestion New Machine Sieve/Mesh

### ISSUE THREAD

**Issue by BrendonGomez** [ImCoolYeah105/Mechanization#6]
#Suggestion

The Sieve/Mesh will filter through gravel, sand, cobblestone and give you various items like gold diamonds gravel etc

**Comment by Darkspyro911** [comment]
so like the T.T.B (The Tempest Box) Sand Shifter

On 6/11/18, BrendonGomez <notifications@github.com> wrote:
> #Suggestion
>
> The Sieve/Mesh will filter through gravel, sand, cobblestone and give you
> various items like gold diamonds gravel etc
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ImCoolYeah105/Mechanization/issues/6


-- 
Marc-Andre Maurice
mauricemarcandre@gmail.com

**Comment by BrendonGomez** [comment]
I have never played with the command block creation known as the tempest box however I have played with a few mods back in the day with sand sifters and they do what a sieve/mesh would do. If the sand sifter is anything like what I explained then yes

**Comment by ImCoolYeah105** [comment]
I don't think something like this fits the progression of Mechanization. It would probably be a bad idea to add to add `1 easy way to get all your resources.` A sifter fits more within a system where mining is impossible or impractical.

**Comment by Darkspyro911** [comment]
hi due to my behavior lately i lost my pc intel further notice please
tell assaing/depress to spread the word on discord thanks

-- 
Marc-Andre Maurice
mauricemarcandre@gmail.com
