### ISSUE TITLE
Crash when attempting to open the Machine Crafting Table GUI.

### ISSUE THREAD

**Issue by Mario3264** [ImCoolYeah105/Mechanization#62]
Crash detailed here, I was testing out 2.1 API Prerelease 1:
[hs_err_pid8236.log](https://github.com/ImCoolYeah105/Mechanization/files/2874570/hs_err_pid8236.log)

**Comment by Mario3264** [comment]
Well, apparently I just have to run "/reload" after the message "[DU] Click here to complete datapack setup." appears. Sorry for the inconvenience.

**Comment by Mario3264** [comment]
But then it crashes again, once I try to open the Machine Crafting Table.

**Comment by ImCoolYeah105** [comment]
Try disabling the resourcepack and let me know what happens, it might be an issue with the custom font (can cause crashes in bizarre cases).
In _most_ cases I can't fix crashes, so this will probably need to be reported to mojang,

**Comment by Mario3264** [comment]
I have disabled the resource pack and it doesn't crash, so perhaps it is likely that the custom font is causing an issue.

**Comment by Mario3264** [comment]
Well, apparently my Intel Graphics driver is broken...

**Comment by Mario3264** [comment]
Well, perhaps it's just an issue on Intel Graphics, even though I installed the official OEM drivers.

**Comment by Mario3264** [comment]
I have confirmed this, as using another computer with an NVIDIA GPU worked fine and didn't crash.
