### ISSUE TITLE
disenchanter will not charge past 2000

### ISSUE THREAD

**Issue by BilboBinSaggin** [ImCoolYeah105/Mechanization#64]
i am currently running the 1.13.2 datapack, and the disenchanter will not charge past 2000kj. I would also like to know how it actually works. Do you put the enchanted item and a regular book into the machine? If so, in what orientation do they need to be in?

**Comment by ImCoolYeah105** [comment]
Different tiers of batteries transfer up to a certain amount: tier 1 only transfers up to 2000 kJ. You will need at least a tier 2 battery to run the disenchanter (up to 4000 kJ).

Just put the item in, no book needed.
