### ISSUE TITLE
Titanium Armour Breaks very fast.

### ISSUE THREAD

**Issue by ChocoKrave** [ImCoolYeah105/Mechanization#67]
Titanium Armour will say it has "1024" hit points left, but will only take around 10 - 20 hits, unbreaking stops this a little bit, but ONLY a little, I haven't tested it with unmodified but can confirm, with all assortments of modifications the armour breaks very quickly.

**Comment by ImCoolYeah105** [comment]
I've had reports of this bug, but I cannot replicate it and have no idea what causes it. Unfortunately I can't fix the bug if I can't find the bug.

**Comment by ImCoolYeah105** [comment]
Probably fixed in 2.1 Prerelease 2.
