### ISSUE TITLE
LogDotZip has done a part two

### ISSUE THREAD

**Issue by BrendonGomez** [ImCoolYeah105/Mechanization#7]
LogDotZip has done a part two but I noticed that the book that he showcased is not in the latest version nor does the titanium sword have a new texture other then diamond. So I'm confused is this a old video that he made and just now decided to post or did you forget to put the new link on curseforge. Is this just old things you decided to remove in the new versions and LogDotZip is showcasing a old version?

**Comment by BrendonGomez** [comment]
Well I really doubt he'd ban me for asking a question. It would be pretty pity. I figured I ask for those who were curious about it as well.

**Comment by Darkspyro911** [comment]
yha sorry about that i was tired it was 12:00 am when i saw that
unfortunately its not out yet if you missed a 1 second of the book it
says wip Work In Process. -Darkspyro911

On 6/15/18, BrendonGomez <notifications@github.com> wrote:
> Well I really doubt he'd ban me for asking a question. It would be pretty
> pity. I figured I ask for those who were curious about it as well.
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/ImCoolYeah105/Mechanization/issues/7#issuecomment-397510852


-- 
Marc-Andre Maurice
mauricemarcandre@gmail.com

**Comment by ImCoolYeah105** [comment]
Update should come out this weekend. It's not quite done yet, still need to add gadgets and assembly to the book, and fix a few bugs.

You should consider joining the discord server for random questions and comments instead of opening a bunch of bug reports: https://discord.gg/6uJ4eJH

**Comment by Darkspyro911** [comment]
ok Thanks @ImCoolYeah105 -Darkspyro911

On 6/15/18, ImCoolYeah105 <notifications@github.com> wrote:
> Update should come out this weekend. It's not quite done yet, still need to
> add gadgets and assembly to the book, and fix a few bugs.
>
> You should consider joining the discord server for random questions and
> comments instead of opening a bunch of bug reports:
> https://discord.gg/6uJ4eJH
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/ImCoolYeah105/Mechanization/issues/7#issuecomment-397650707


-- 
Marc-Andre Maurice
mauricemarcandre@gmail.com
