### ISSUE TITLE
Error when loading data pack on Spigot 1.14

### ISSUE THREAD

**Issue by corndog2000** [ImCoolYeah105/Mechanization#70]
The server displays an error when loading the datapack. This is because the datapack is looking for minecraft:sign but in 1.14 they added signs for each type of wood. So there isn't a plain sign any more.

Here is the server log: [https://pastebin.com/dNpUp7Fe](https://pastebin.com/dNpUp7Fe)

**Comment by ImCoolYeah105** [comment]
Currently, Mechanization is not compatible with 1.14. An update is almost ready, but I have final exams next week so I'm not sure when I'll get it out.
