### ISSUE TITLE
ores not smelting

### ISSUE THREAD

**Issue by Sj3mp0t** [ImCoolYeah105/Mechanization#76]
i cant seem to smelt my ores in the latest version, can someone help. i have tried putting it in an furnace an in the machine crafting table with a flint and steel but it isnt working.

**Comment by ImCoolYeah105** [comment]
You smelt ores in a furnace. If the furnace was placed before adding Mech/DU or was placed via world gen (ie. villages) you will need to break and replace the furnace.

If breaking and replacing doesn't work, try these debug steps:
1. Are you running in a non-vanilla environment? (Forge, fabric, spigot, bukkit, optifine, etc).
2. Run /reload. Make sure it says "[Loaded Mechanization v2.1.0c]" and "[Loaded Datapack Utils v2.0.1a]" in chat. Then, see if the problem persists.

**Comment by Sj3mp0t** [comment]
ty, it is working now
