### ISSUE TITLE
Flight upgrade is strange

### ISSUE THREAD

**Issue by Funnymeme1** [ImCoolYeah105/Mechanization#77]
According to the wiki, it says to look up and jump to fly. Using mechanization v2.1.1, whenever I'm on the surface and jump, flight will activate. Whenever I'm underground, it completely refuses to activate.

**Comment by ImCoolYeah105** [comment]
Looks like I forgot to test for cave air when activating flight. Small change, it'll be fixed next update.

**Comment by ImCoolYeah105** [comment]
Fixed in 2.2.0
