### ISSUE TITLE
Can't get resource pack. Can i get some help please?

### ISSUE THREAD

**Issue by bonjour12323** [ImCoolYeah105/Mechanization#79]

**Comment by ImCoolYeah105** [comment]
"Can't get resourcepack" as in it won't download? That's a little odd as Github is usually very reliable. You can always try an alternative source like [Planet Minecraft](https://www.planetminecraft.com/data-pack/mechanization/) or [Curseforge](https://www.curseforge.com/minecraft/texture-packs/mechanization-resources).

**Comment by bonjour12323** [comment]
Sorry forgot I needed it in the rescorces folder my bad
