### ISSUE TITLE
scarcity of minerals

### ISSUE THREAD

**Issue by groovy-d** [ImCoolYeah105/Mechanization#80]
So far in demolishing many full chunks down to bedrock, both byhand and by /fill command I've found 3 basic, 2 of the middle and 2 superior. thats it.
I am running a realms server, if that makes a difference.

Are minerals supposed to be this rare? In the 2 months I've been running the server, which I created and before ever setting foot on the server installed the datapacks and restarted it.

Thanks, its a great idea and I hope it gets better and better  :)

**Comment by ImCoolYeah105** [comment]
Awhile back I fixed some bugs it ore gen which probably dropped the ore density, but that sounds much lower then it should be. I'll take a look at it.

**Comment by ImCoolYeah105** [comment]
Should be fixed in 2.2.0
