### ISSUE TITLE
about ore smelting

### ISSUE THREAD

**Issue by pyrosoda** [ImCoolYeah105/Mechanization#81]
i can`t smelt or craft an ore in machine crafting table and furnaces

**Comment by simon511000** [comment]
Are you using spigot?

**Comment by pyrosoda** [comment]
ah.....I read similar problems in discord chats and found out replacing the furnace makes it work. However, I think it is a bug anyway.

**Comment by ImCoolYeah105** [comment]
The hacked-in custom smelting system I use requires every furnace to be marked with an entity. Unfortunately, I can't retroactively add this entity to existing furnaces so you will have to break and replace them. Nothing I can do about it.
