### ISSUE TITLE
Can't make T2 Machine Frame

### ISSUE THREAD

**Issue by BorealBlizzard** [ImCoolYeah105/Mechanization#83]
1. Datapacks
Mechanization & Datapack Utilities

2. Screenshot
![2019-12-30_00 54 14](https://user-images.githubusercontent.com/33204005/71571294-383e6000-2a9f-11ea-9360-a3d290ef7702.png)

3. What environment are you running the datapack?
Just Vanilla Single Player

4. What if happening vs. what you expect to happen?
Trying to use the Machine crafting table to make T2 Machine Frames but nothing shows up in the output.

**Comment by BorealBlizzard** [comment]
Noticed that v2.2.1 came out, going to try it see if it happens to fix the issue.

**Comment by BorealBlizzard** [comment]
> Noticed that v2.2.1 came out, going to try it see if it happens to fix the issue.

Did not fix the problem

**Comment by BorealBlizzard** [comment]
Also found out that I cannot create Machine upgrades

**Comment by ImCoolYeah105** [comment]
I can craft both in my test world, make sure the recipe is correct:
- Machine Frame: 8 red stained glass, 4 structural ingots, 5 steel ingots
- Upgrade: 4 steel ingots, 2 structural ingots, 2 conductive ingots.

**Comment by BorealBlizzard** [comment]
OOOH ok, thats what the problem was. the colors of some of the custom ingots are too similar at times so that was what messed me up. Maybe you should put the names of the items needed under the crafting recipe in the wiki to solve issues like this is the future.
