### ISSUE TITLE
I Can't Get The Quarry To Work

### ISSUE THREAD

**Issue by 1403gavin** [ImCoolYeah105/Mechanization#84]
it said right click to set a boundary but it open the inventory

**Comment by ImCoolYeah105** [comment]
Please use the bug template:

1. What datapack(s) do you have installed (including ones made by me- include version if possible).

2. Run /reload. Copy/paste or post a screenshot of what appears in chat (should say [Loaded <datapack> <version>]).

3. What environment are you running the datapack? (Vanilla single player, Vanilla multiplayer, Forge, fabric, spigot, bukkit, paper, optifine, realms, etc). Please specify exact Minecraft version as well.

4. What if happening vs. what you expect to happen?

**Comment by 1403gavin** [comment]
1. just the mechinization ones 2.1.1 and 2.0.2

2. i cant use /reload because i dont have cheats

3. VSP w/OptiFine

4. the quarry is opening the machine instead of selecting the boundary of the quarry

**Comment by ImCoolYeah105** [comment]
I generally don't support outdated versions so I'm closing the issue, but I'll still see if I can help:

As a recommendation, you should always enable cheats when using datapacks as debugging usually requires cheats.

There should be an invisible entity in front of you that prevents clicking on the quarry, and it sounds like it's being not being summoned. See if the multi-meter has the same issue.

If worst comes to worst, the wrench has a slightly longer reach then right clicking on blocks, so if you stand back far enough you won't click on the quarry but can still use the wrench.

**Comment by 1403gavin** [comment]
it worked thank you
