### ISSUE TITLE
Cannot craft Titanium tools in 1.15.1

### ISSUE THREAD

**Issue by cobaltwarrior19** [ImCoolYeah105/Mechanization#85]
1. What datapack(s) do you have installed (including ones made by me- include version if possible).
autocraft-1561990610
Chest Mover Datapack v1.1
DatapackUtilities v2.1.2
magic-sorting-system
magic-sorting-system-master
player graves v1.6.1
smartsaplings-1556232600
treecapitator-v2.5.4
vein_miner v.1.14

However, this bug has been duplicated in a world running all by itself.

2. Run /reload. Copy/paste or post a screenshot of what appears in chat (should say [Loaded <datapack> <version>]).

> [Loaded Datapack Utils v2.1.2]

> [Loaded Mechanization v2.2.1]

3. What environment are you running the datapack? (Vanilla single player, Vanilla multiplayer, Forge, fabric, spigot, bukkit, paper, optifine, realms, etc). Please specify exact Minecraft version as well.

Datapack is being run in Vanilla single player v1.15.1, and Vanilla multiplayer (LAN) v1.15.1

4. What if happening vs. what you expect to happen?
What is happening: When I place the ingredients into the crafting grid (following the recipe in the datapack's crafting guide, and in the readme),  of the Machine Crafting Table, nothing happens. I don't get a Titanium pickaxe.

**Comment by ImCoolYeah105** [comment]
Titanium equipment has special recipes that use the diamond version as an ingrediant (see the [wiki](https://github.com/ImCoolYeah105/Mechanization/wiki/Titanium-Tools)).
Since this is likely in incorrect recipe I am closing the issue.

**Comment by cobaltwarrior19** [comment]
![Inked2020-01-17_10 29 29_LI](https://user-images.githubusercontent.com/11684705/72628766-99c25380-3914-11ea-92cb-78b13e55cf1a.jpg)


enclosed is an image of my issue.

**Comment by ImCoolYeah105** [comment]
Updating to Mechanization 2.2.1b should resolve the issue. If not let me know.
