### ISSUE TITLE
Issue with inventory crafting

### ISSUE THREAD

**Issue by maicol07** [ImCoolYeah105/Mechanization#87]
1. What datapack(s) do you have installed (including ones made by me- include version if possible).
![immagine](https://user-images.githubusercontent.com/9463142/76683438-4e6ead80-6604-11ea-9a49-1e3adeab1f4d.png)

2. Run /reload. Copy/paste or post a screenshot of what appears in chat (should say [Loaded <datapack> <version>]).
Plugin gets loaded well

3. What environment are you running the datapack? (Vanilla single player, Vanilla multiplayer, Forge, fabric, spigot, bukkit, paper, optifine, realms, etc). Please specify exact Minecraft version as well.
Vanilla Multiplayer (20w11a server with 2 friends)

4. What if happening vs. what you expect to happen?
When I enable Mechanization I can't do inventory crafting (when I place items in inventory crafting grid they disappear)

**Comment by ImCoolYeah105** [comment]
It's probably a snapshot bug. I won't be supporting snapshots until there more stable.

**Comment by ImCoolYeah105** [comment]
afaik this was just a snapshot bug
