### ISSUE TITLE
can't get autofisher to work

### ISSUE THREAD

**Issue by NKSHV** [ImCoolYeah105/Mechanization#88]
1. What datapack(s) do you have installed (including ones made by me- include version if possible).
datapackutilities-v2-1-3a.zip
mechanization-v2-2-2.zip
Anti_Ender-Grief_1.0.zip (only modifies enderman_holdable.json)
VanillaTweaks_c929844.zip (only recipes)

2. Run /reload. Copy/paste or post a screenshot of what appears in chat (should say [Loaded <datapack> <version>]).
loaded datapackutilities 2.1.3 and mechanization 2.2.2

3. What environment are you running the datapack? (Vanilla single player, Vanilla multiplayer, Forge, fabric, spigot, bukkit, paper, optifine, realms, etc). Please specify exact Minecraft version as well.
vanilla single player minecraft 1.15.2

4. What if happening vs. what you expect to happen?
So when I first placed autofisher flames appeared on top of it so it worked, but I didn't know how it works so I removed it. Than after I red that it drops items under it, I placed it again in the same exact spot but now it does not work. I tried placing it in other spots, icluding ocean where there is definitely 5x5x5 space around it and it refuses to work. There is 2000 energy stored in it.

**Comment by ImCoolYeah105** [comment]
Could you post a screen shot of you're setup? It sounds like you're using it correctly but I would like to make sure.

**Comment by NKSHV** [comment]
> Could you post a screen shot of your setup? It sounds like you're using it correctly but I would like to make sure.

[https://sun1-88.userapi.com/2M9hn2yRQPoCgb9jk9VNQ73u-LwofuBNOnAkLQ/lAbXqX9jREs.jpg](url)

**Comment by ImCoolYeah105** [comment]
The 5x5x5 area of water required is centered around the auto fisher, which means you need water bellow it in addition of water above it, like this:

![Imgur](https://imgur.com/VdwBaj1)

Looks like there isn't a bug here, but if it continuous to not work let me know.
