### ISSUE TITLE
I Cant Find The Tutorial World

### ISSUE THREAD

**Issue by aderey** [ImCoolYeah105/Mechanization#9]
Please Help Me

**Comment by ImCoolYeah105** [comment]
I do not have any tutorial worlds publicly available. However, I will be uploading some videos to my channel that cover everything in Mechanization soon-ish, which should help.

**Comment by Darkspyro911** [comment]
because if you look in advancements that's your tutorial

On 6/17/18, aderey <notifications@github.com> wrote:
> Logdotzip Has the mechanization tutorial world and we cant get it why
>
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/ImCoolYeah105/Mechanization/issues/9#issuecomment-397860178


-- 
Marc-Andre Maurice
mauricemarcandre@gmail.com
