### ISSUE TITLE
The quarry seem not working :/ 

### ISSUE THREAD

**Issue by KileGreen** [ImCoolYeah105/Mechanization#91]
Hi, 

i'm actually testing this datapack on a realm and the tier 1 machines works correctly but the quarry doesn't .... we try with a tiers 1 and 2 battery and it doesn't want to dig 

there is anything we don't do correctly ? we fix boundaries with fences right click with the wrench and nothin happen :/

**Comment by KileGreen** [comment]
we have the 2.2.2 version

**Comment by ImCoolYeah105** [comment]
This is an issue with Realms deleting files from datapacks. Unfortunately there is nothing I can do to fix it.
