### ISSUE TITLE
Chunk Loader not craftable

### ISSUE THREAD

**Issue by CornFlakes1991** [ImCoolYeah105/Mechanization#93]
1. What datapack(s) do you have installed? 
Auto Utilities Vein Mining v1.1.2
Datapack Utils v2.1.4
Mechanization v2.2.2

2. 
![RCt5BU](https://user-images.githubusercontent.com/26132979/82955517-5311f380-9faf-11ea-96ae-b42f3f5850a1.png)

3. Vanilla Multiplayer 1.15.2 with optifine.

4. What if happening vs. what you expect to happen?

Chunk loader do not appear in the Mechanization Workbench

![J8EUHi](https://user-images.githubusercontent.com/26132979/82955617-8785af80-9faf-11ea-9f6c-238e70b78804.png)

**Comment by ImCoolYeah105** [comment]
Hmm, thought I put a note on the wiki that the chunk loader was removed in 1.15.2. Might re-add at some point but currently doesn't exist.

**Comment by CornFlakes1991** [comment]
No problem. Love the data pack! keep it up!
