### ISSUE TITLE
mechanization disenchanter cant be up than 2000 kj

### ISSUE THREAD

**Issue by chewbakaya** [ImCoolYeah105/Mechanization#94]
1. What datapack(s) do you have installed (including ones made by me- include version if possible).

2. Run /reload. Copy/paste or post a screenshot of what appears in chat (should say [Loaded <datapack> <version>]).

3. What environment are you running the datapack? (Vanilla single player, Vanilla multiplayer, Forge, fabric, spigot, bukkit, paper, optifine, realms, etc). Please specify exact Minecraft version as well.

4. What if happening vs. what you expect to happen?

**Comment by chewbakaya** [comment]
all is write in the title

**Comment by chewbakaya** [comment]
it is ok ty

**Comment by ImCoolYeah105** [comment]
disenchanter requires a T2 battery or higher to use
