### ISSUE TITLE
Base Upgrade isn't in the recipes book

### ISSUE THREAD

**Issue by Rivera071** [ImCoolYeah105/Mechanization#95]
I was trying to get some of the pickaxe upgrades, but in the book isn't the craft of the base upgrade, then i found it on this page and i did them, but when i have the pickaxe with the upgrade it doesn't work. I don't know if is a bug or i don't know how to put the upgrades, but please help me, couse the recipes and tips from this page aren't for the new version of the datapack.

**Comment by ImCoolYeah105** [comment]
Most upgrades require power from a portable battery in you're hotbar.

**Comment by Rivera071** [comment]
Thanks you!!!

**Comment by Rivera071** [comment]
Hello, i tried with the portable battery and it doesn`t work. Then i put the armor upgrade on my boots and that don`t work to. I think that im doing something wrong so can you explain me how to use the tinker table please (I'm playing on realms)

![2020-06-14_20 16 37](https://user-images.githubusercontent.com/66894311/84606489-a96aa780-ae74-11ea-9125-77d4831df410.png)
